# This file was generated by GoReleaser. DO NOT EDIT.
cask "fm" do
  name "fm"
  desc "Safe, read-oriented CLI for Fastmail email via JMAP"
  homepage "https://github.com/cboone/fm"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fm"

  on_macos do
    on_intel do
      url "https://github.com/cboone/fm/releases/download/v#{version}/fm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/cboone/fm/"
      sha256 "faab46b9a16e0c4158e09014211c6b39ee2a6e8ce9999e3968f320f4ff75c556"
    end
    on_arm do
      url "https://github.com/cboone/fm/releases/download/v#{version}/fm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/cboone/fm/"
      sha256 "05ecad3ae80454bc2ec4fbb48c618b83256b448c2aa392e83137b9fb3a616b20"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cboone/fm/releases/download/v#{version}/fm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/cboone/fm/"
      sha256 "c492115ee05ee656b751629ba1b1710e3f19a8dcdf3bcc2600a0f389b5a932c2"
    end
    on_arm do
      url "https://github.com/cboone/fm/releases/download/v#{version}/fm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/cboone/fm/"
      sha256 "a6fdf9f0ccebf35b56a394bfb740d8aef0ffa16b41e3935bdec48a10036449d7"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required
end
