# This file was generated by GoReleaser. DO NOT EDIT.
cask "snappy" do
  name "snappy"
  desc "Automatically increase your Time Machine snapshot frequency (macOS only)"
  homepage "https://github.com/cboone/snappy"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snappy"

  on_macos do
    on_intel do
      url "https://github.com/cboone/snappy/releases/download/v#{version}/snappy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/cboone/snappy"
      sha256 "c708aa8e16d96d4cbe213e4095180eb5a53c04178ffb0459fed16c6d73571a8d"
    end
    on_arm do
      url "https://github.com/cboone/snappy/releases/download/v#{version}/snappy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/cboone/snappy"
      sha256 "e8cdd72c1777a8a6ef5e1bd138838e5a2c142019b0cde5ad2c1706c5c65c786a"
    end
  end

  postflight do
    xattr -dr com.apple.quarantine "#{staged_path}/snappy"
  end

  # No zap stanza required
end
