# This file was generated by GoReleaser. DO NOT EDIT.
cask "snappy-tm" do
  name "snappy-tm"
  desc "Automatically increase your Time Machine snapshot frequency (macOS only)"
  homepage "https://github.com/cboone/snappy"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snappy"
  manpage "share/man/man1/snappy.1"

  on_macos do
    on_intel do
      url "https://github.com/cboone/snappy/releases/download/v#{version}/snappy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/cboone/snappy"
      sha256 "8c74062d4a7cc49c8b645a12b5cfc86a21cb064f002f35916a7a0d90442c2626"
    end
    on_arm do
      url "https://github.com/cboone/snappy/releases/download/v#{version}/snappy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/cboone/snappy"
      sha256 "5108871798cce1d8409d85695c03b3223df041cb88842a29633b89e4de12705f"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/snappy"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/etc/bash_completion.d"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/snappy.bash", "#{HOMEBREW_PREFIX}/etc/bash_completion.d/snappy"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/zsh/site-functions"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/_snappy", "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_snappy"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/snappy.fish", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/snappy.fish"]
  end

  caveats do
    "To run snappy automatically in the background:\n  snappy service install\n\nTo stop the background service:\n  snappy service uninstall"
  end

  uninstall launchctl: [
      "com.cboone.snappy",
    ]

  # No zap stanza required
end
