# This file was generated by GoReleaser. DO NOT EDIT.
cask "snappy" do
  name "snappy"
  desc "Automatically increase your Time Machine snapshot frequency (macOS only)"
  homepage "https://github.com/cboone/snappy"
  version "0.8.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snappy"

  on_macos do
    on_intel do
      url "https://github.com/cboone/snappy/releases/download/v#{version}/snappy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/cboone/snappy"
      sha256 "c352b7c8caf1e47ed55492832be0c8777a47d0bf00dee6779f59735aa99f9845"
    end
    on_arm do
      url "https://github.com/cboone/snappy/releases/download/v#{version}/snappy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/cboone/snappy"
      sha256 "96581cf6955dd9fe9ba3c1a1b5aa123267927f523b85becbdaf1dea09a0721e7"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/snappy"]
  end

  caveats do
    "To run snappy automatically in the background:"
    "  snappy service install"
    ""
    "To stop the background service:"
    "  snappy service uninstall"
  end

  uninstall launchctl: [
      "com.cboone.snappy",
    ]

  # No zap stanza required
end
