# This file was generated by GoReleaser. DO NOT EDIT.
cask "snappy-tm" do
  name "snappy-tm"
  desc "Automatically increase your Time Machine snapshot frequency (macOS only)"
  homepage "https://github.com/cboone/snappy"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snappy"
  manpage "share/man/man1/snappy.1"

  on_macos do
    on_intel do
      url "https://github.com/cboone/snappy/releases/download/v#{version}/snappy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/cboone/snappy"
      sha256 "5589df765f59daf0552aebe9fb4599275c6f4b1bf269c9a855adbf1b8acaaecb"
    end
    on_arm do
      url "https://github.com/cboone/snappy/releases/download/v#{version}/snappy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/cboone/snappy"
      sha256 "3e9de42adf237d287fe2382a2a5e9a6986c6d86c3c1af24d5a9fa52ffbb9fa73"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/snappy"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/etc/bash_completion.d"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/snappy.bash", "#{HOMEBREW_PREFIX}/etc/bash_completion.d/snappy"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/zsh/site-functions"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/_snappy", "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_snappy"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/snappy.fish", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/snappy.fish"]
  end

  caveats do
    "To run snappy automatically in the background:\n  snappy service install\n\nTo stop the background service:\n  snappy service uninstall"
  end

  uninstall launchctl: [
      "com.cboone.snappy",
    ]

  # No zap stanza required
end
