# This file was generated by GoReleaser. DO NOT EDIT.
cask "snappy" do
  name "snappy"
  desc "Automatically increase your Time Machine snapshot frequency (macOS only)"
  homepage "https://github.com/cboone/snappy"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snappy"

  on_macos do
    on_intel do
      url "https://github.com/cboone/snappy/releases/download/v#{version}/snappy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/cboone/snappy"
      sha256 "d92b619a751798b4f5ca2526327b219531b23932dbea501f21fc50dc519cf845"
    end
    on_arm do
      url "https://github.com/cboone/snappy/releases/download/v#{version}/snappy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/cboone/snappy"
      sha256 "2b0f8af206180864c50533e19cc2032c0974401ab1c9bd4e2d2bfc97623bfe60"
    end
  end

  postflight do
    xattr -dr com.apple.quarantine "#{staged_path}/snappy"
  end

  caveats do
    "To run snappy automatically in the background:"
    "  snappy service install"
    ""
    "To stop the background service:"
    "  snappy service uninstall"
  end

  uninstall launchctl: [
      "com.cboone.snappy",
    ]

  # No zap stanza required
end
