# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bopca < Formula
  desc "Run LLM agents in lightweight macOS VMs"
  homepage "https://github.com/cboone/bopca"
  version "0.8.1"
  license "MIT"

  depends_on "container"
  depends_on "go" => :build
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/cboone/bopca/releases/download/v0.8.1/bopca-darwin-arm64.tar.gz"
    sha256 "81f98aad67546ac4812b26b55f07233373a5df5942dcd87e3f1ed4cafd8b40f6"

    define_method(:install) do
      bin.install "bopca"
      (share/"bopca").install "Containerfile"
      (share/"bopca").install "config/bopca.example.yaml"
      (share/"bopca/config").install Dir["config/*"]
      generate_completions_from_executable(bin/"bopca", "completion")
      man1.install Dir["man/man1/*"]
    end
  end

  depends_on :macos
  depends_on arch: :arm64

  def caveats
    <<~EOS
      Optional: Set up DNS for container hostnames:
        sudo container system dns create test
        container system property set dns.domain test

      Configuration file locations:
        Project: .bopca.yaml or .bopca.yml
        User:    $XDG_CONFIG_HOME/bopca/bopca.yaml or bopca.yml (default: ~/.config/bopca/bopca.yaml or bopca.yml)

      Example config: #{share}/bopca/bopca.example.yaml
    EOS
  end

  test do
    assert_match "bopca", shell_output("#{bin}/bopca --help")
    assert_match version.to_s, shell_output("#{bin}/bopca version")
  end
end
