# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fm < Formula
  desc "Safe, read-oriented CLI for Fastmail email via JMAP"
  homepage "https://github.com/cboone/fm"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cboone/fm/releases/download/v0.2.0/fm_0.2.0_darwin_amd64.tar.gz"
      sha256 "0c1db693e47f075d7cefd1d5494c99e8f40e6657df28f7e9fda0cb01b2390bdb"

      def install
        bin.install "fm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cboone/fm/releases/download/v0.2.0/fm_0.2.0_darwin_arm64.tar.gz"
      sha256 "92277b7f66c8569fa03681c3b59d4259824fb9e5b56b8add1c09b03dc738a9d5"

      def install
        bin.install "fm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cboone/fm/releases/download/v0.2.0/fm_0.2.0_linux_amd64.tar.gz"
      sha256 "81fa3450690b1d23bcc07ed8fbf4f29b23122cf06c95742605d9b031561fc692"
      def install
        bin.install "fm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cboone/fm/releases/download/v0.2.0/fm_0.2.0_linux_arm64.tar.gz"
      sha256 "9e491317641771c08e8e006086c25ee3605f412fa8a40688004d3a677d41c4e7"
      def install
        bin.install "fm"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fm --version")
  end
end
