# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhProblemas < Formula
  desc "TUI for GitHub issue management"
  homepage "https://github.com/cboone/gh-problemas"
  version "0.1.0"
  license "MIT"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cboone/gh-problemas/releases/download/v0.1.0/gh-problemas_0.1.0_darwin_amd64.tar.gz"
      sha256 "bd48d93f073ddad2fe525bb5ac78ca137c5c4416450471fb49727196b712f520"

      def install
        bin.install "gh-problemas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cboone/gh-problemas/releases/download/v0.1.0/gh-problemas_0.1.0_darwin_arm64.tar.gz"
      sha256 "db71ff7af22898126f4577143d05f3236864e3ea1031573b0edeeaea715ab104"

      def install
        bin.install "gh-problemas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cboone/gh-problemas/releases/download/v0.1.0/gh-problemas_0.1.0_linux_amd64.tar.gz"
      sha256 "0678b9c08e4bb292ece46ad5f8e19108b289e6d5d46b4640717fad5b9756d2c7"
      def install
        bin.install "gh-problemas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cboone/gh-problemas/releases/download/v0.1.0/gh-problemas_0.1.0_linux_arm64.tar.gz"
      sha256 "f78a87f5cdb103fcc74d3932dc9b7ba688584f34423b0cf89d87c8d95f54be0e"
      def install
        bin.install "gh-problemas"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gh-problemas --version")
  end
end
