# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snappy < Formula
  desc "Automatically increase your Time Machine snapshot frequency (macOS only)"
  homepage "https://github.com/cboone/snappy"
  version "0.3.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/cboone/snappy/releases/download/v0.3.1/snappy_0.3.1_darwin_amd64.tar.gz"
    sha256 "7af852ee0afdf3914e10bafb5c2e3d03e121fec54bb17b0a92617b7fe6b6049d"

    define_method(:install) do
      bin.install "snappy"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/cboone/snappy/releases/download/v0.3.1/snappy_0.3.1_darwin_arm64.tar.gz"
    sha256 "9d2fbba3cbfed0d8871fa5a7408db089577065b778c553dced89eeff7d761fc4"

    define_method(:install) do
      bin.install "snappy"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/snappy --version")
  end
end
